[package]
name = "lmerge"
version = "0.1.0"
edition = "2024"
description = "A lightweight tool for merging and chronologically sorting log files"

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
env_logger = "0.11.6"
log = "0.4.26"
