name: Release Binaries

on:
  push:
    tags:
      - "bump-v*"
      - "mm2glab-v*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ""
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: ""

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Extract Binary Name and Version
        id: tag_info
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          BINARY_NAME=$(echo $TAG_NAME | cut -d'-' -f1)
          VERSION=$(echo $TAG_NAME | cut -d'v' -f2)
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Binary
        run: cargo build --release --package ${{ env.BINARY_NAME }} --target ${{ matrix.target }}

      - name: Rename Binary
        run: mv target/${{ matrix.target }}/release/${{ env.BINARY_NAME }} target/${{ env.BINARY_NAME }}-${{ env.VERSION }}-${{ matrix.target }}${{ matrix.ext }}

      - name: Upload Binary
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          files: target/${{ env.BINARY_NAME }}-${{ env.VERSION }}-${{ matrix.target }}${{ matrix.ext }}
          generate_release_notes: true
